### ISSUE TITLE
Question: is it possible to override the default differ output for a nested type

### ISSUE THREAD

**Issue by ursenzler** [d-edge/Diffract#21]
I have a data structure that contains a deeply nested NodaTime.LocalTime. The diff output is too detailed to be human-readable. I'd like to override the diff output for the LocalTime to show "hh:mm". Is there a way to achieve this?
I see that I can pass an `IDiffer` to the diff function. But I only want a replacement for `LocalTime` with as little effort as possible.

Thanks for this great library!

**Comment by Tarmil** [comment]
You can create an IDiffer that can handle any type, and will use your custom code to handle any nested `LocalTime`. Unfortunately the code is a bit unwieldy:

```fsharp
type LocalTimeDiffer() =
    interface ICustomDiffer with
        member this.GetCustomDiffer<'T>(differFactory, shape) =
            if shape.Type = typeof<'T> then
                { new IDiffer<LocalTime> with
                    member _.Diff(x1, x2) =
                        // This is where you put your custom diffing code:
                        if x1 = x2 then
                            None
                        else
                            Diff.Value(x1.ToString("hh:mm"), x2.ToString("hh:mm"))
                            |> Some }
                |> unbox<IDiffer<'T>
                |> Some
            else
                None

// It is important that this is a top-level generic non-function value.
// This will generate the full differ once per type 'T, whereas a function would re-generate it on every call.
let myDiffer<'T> = LocalTimeDiffer().GetDiffer<'T>()

// Example use:

type Message = { time: LocalTime }

Differ.Assert({ time = LocalTime(13, 37) }, { time = LocalTime(16, 20) }, myDiffer)
// Output:
// time Expect = 13:37
//      Actual = 16:20
```

If you want to provide custom diffing for multiple types, you can use CombinedCustomDiffer:

```fsharp
type LocalTimeDiffer() = // ...

type InstantDiffer() = // ...

let combinedDiffer = CombinedCustomDiffer [ LocalTimeDiffer(); InstantDiffer() ]
let myDiffer<'T> = combinedDiffer.GetDiffer<'T>()
```

It should be possible to add functions to the library that would simplify the above. It is definitely needed, along with some documentation 😄

**Comment by ursenzler** [comment]
When I run the test in this code:

```fsharp
module DiffractCustomDiffer

open DEdge.Diffract
open FsToolkit.ErrorHandling
open NodaTime
open Xunit

type LocalTimeDiffer() =
    interface ICustomDiffer with
        member this.GetCustomDiffer<'T>(differFactory, shape) =
            if shape.Type = typeof<'T> then
                { new IDiffer<LocalTime> with
                    member _.Diff(x1, x2) =
                        // This is where you put your custom diffing code:
                        if x1 = x2 then
                            None
                        else
                            Diff.Value(x1.ToString(), x2.ToString())
                            |> Some }
                |> unbox<IDiffer<'T>>
                |> Some
            else
                None

// It is important that this is a top-level generic non-function value.
// This will generate the full differ once per type 'T, whereas a function would re-generate it on every call.
let myDiffer<'T> = LocalTimeDiffer().GetDiffer<'T>()

// Example use:

type Message = { time: LocalTime }

[<Fact>]
let foo () =
    Differ.Assert({ time = LocalTime(13, 37) }, { time = LocalTime(16, 20) }, myDiffer)
    
```

then I get the following error message:

```
System.InvalidCastException
Unable to cast object of type 'Pipe #2 input at line 12@12' to type 'DEdge.Diffract.IDiffer`1[DiffractCustomDiffer+Message]'.
   at Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicFunctions.UnboxGeneric[T](Object source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\prim-types.fs:line 643
   at DiffractCustomDiffer.LocalTimeDiffer.DEdge.Diffract.ICustomDiffer.GetCustomDiffer[T](IDifferFactory differFactory, TypeShape`1 shape) in C:\Projects\Playground\FSharp\DiffractCustom.fs:line 20
   at DEdge.Diffract.DifferImpl.diffWith[T](ICustomDiffer custom, Dictionary`2 cache)
   at DiffractCustomDiffer.myDiffer[T]() in C:\Projects\Playground\FSharp\DiffractCustom.fs:line 27
   at DiffractCustomDiffer.foo() in C:\Projects\Playground\FSharp\DiffractCustom.fs:line 35
```

What did I miss?

And what do you mean by "top-level" exactly?

Thanks for your help!

**Comment by Tarmil** [comment]
Oh my bad, there's a mistake in my code; it should be `if shape.Type = typeof<LocalTime> then` at the beginning of `GetCustomDiffer`.

Top-level means it should be declared in a module, rather than locally in a test method.

**Comment by ursenzler** [comment]
Many thanks. Works perfectly!
